// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDatGpBF5eh39NkfkOmgkGz382XGlcUhco',
    appId: '1:898210077962:web:748a8a4bf8ecb42879eef3',
    messagingSenderId: '898210077962',
    projectId: 'chatapp-d1031',
    authDomain: 'chatapp-d1031.firebaseapp.com',
    storageBucket: 'chatapp-d1031.firebasestorage.app',
    measurementId: 'G-JZD5BQFJZ4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvNaOJvcsMFxjYPZ1TtxO3vVjFRjHzf04',
    appId: '1:898210077962:ios:230fcc4a5a48338079eef3',
    messagingSenderId: '898210077962',
    projectId: 'chatapp-d1031',
    storageBucket: 'chatapp-d1031.firebasestorage.app',
    iosBundleId: 'com.example.chatAppUsingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvNaOJvcsMFxjYPZ1TtxO3vVjFRjHzf04',
    appId: '1:898210077962:ios:230fcc4a5a48338079eef3',
    messagingSenderId: '898210077962',
    projectId: 'chatapp-d1031',
    storageBucket: 'chatapp-d1031.firebasestorage.app',
    iosBundleId: 'com.example.chatAppUsingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDatGpBF5eh39NkfkOmgkGz382XGlcUhco',
    appId: '1:898210077962:web:270db8089e46db2979eef3',
    messagingSenderId: '898210077962',
    projectId: 'chatapp-d1031',
    authDomain: 'chatapp-d1031.firebaseapp.com',
    storageBucket: 'chatapp-d1031.firebasestorage.app',
    measurementId: 'G-JH301N40JJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaLyVH_ZxgmV_k7LQH6I3nKa6HaGCgqj8',
    appId: '1:898210077962:android:1cadcc3ce1f75c9879eef3',
    messagingSenderId: '898210077962',
    projectId: 'chatapp-d1031',
    storageBucket: 'chatapp-d1031.firebasestorage.app',
  );

}